language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t eunsongpark/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true eunsongpark/react-test-app npm run test

after_success:
  - docker build -t eunsongpark/docker-frontend ./frontend
  - docker build -t eunsongpark/docker-backend ./backend
  - docker build -t eunsongpark/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push eunsongpark/docker-frontend
  - docker push eunsongpark/docker-backend
  - docker push eunsongpark/docker-nginx
